### ISSUE TITLE
Raids (Alliance) does not open duty menu

### ISSUE THREAD

**Issue by Cryotechnic** [MidoriKami/DailyDuty#230]
When the Raids (Alliance) module is enabled, if the "Clickable Link" checkbox is checked, clicking on the entry in the Todo List generates the following error in `xllogs` and does not select the duty in the duty list, nor open the duty menu:

```19:33:39.078 | ERR | [AddonEventManager] Exception in PluginEventList custom event invoke.
System.InvalidOperationException: Sequence contains no elements
	   at System.Linq.ThrowHelper.ThrowNoElementsException()
	   at DailyDuty.Classes.PayloadController.<>c.<GetDelegateForPayload>b__5_5(UInt32 _, SeString _) in /work/repo/DailyDuty/Classes/PayloadController.cs:line 80
	   at KamiToolKit.Nodes.NodeBase.HandleEvents(AddonEventType atkEventType, IntPtr atkUnitBase, IntPtr atkResNode) in /work/repo/KamiToolKit/Nodes/NodeBase/NodeBase.Events.cs:line 102
	   at Dalamud.Game.Addon.Events.PluginEventController.PluginEventListHandler(AtkEventListener* self, AtkEventType eventType, UInt32 eventParam, AtkEvent* eventPtr, AtkEventData* eventDataPtr) in C:\goatsoft\companysecrets\dalamud\\Game\Addon\Events\PluginEventController.cs:line 195
```

Furthermore, after completing the weekly alliance raid, the corresponding completion status for the Raids (Alliance) module does not change to "Complete", even though it is indicated that it is by the green circle:

![image](https://github.com/user-attachments/assets/b449a66c-2aa3-4fc9-a669-3249dccc4b3d)

A "fix" I have found to change the module status to "Complete" is to set the "Target Drop Count" field to `-1`, though I am unsure if that is a desired result.

**Comment by MidoriKami** [comment]
The green circle is NOT the completion state of the module, it's the enabled state.

**Comment by MidoriKami** [comment]
delete your raidsalliance.data.json file in your plugin configuration folder

**Comment by MidoriKami** [comment]
Stale, if issue persists include additional information and reopen.
